import type { Metadata } from "next";
import { Baloo_2, Baloo_Da_2 } from "next/font/google";
import { Providers } from "./providers";

const baloo2 = Baloo_2({
  variable: "--font-baloo-2",
  subsets: ["latin"],
  display: "swap",
});

const balooDa2 = Baloo_Da_2({
  variable: "--font-baloo-da-2",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://yourdomain.com",
    siteName: "Create Next App",
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${baloo2.variable} ${balooDa2.variable}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
